exclude: '^docs/|/migrations/|devcontainer.json'
default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.10.4
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        # additional_dependencies: [jupytext]  # optional, only if you're using Jupytext
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]
      - id: nbqa-isort
        args: ["--float-to-top"]
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
